### ISSUE TITLE
parcel version in dependencies incompatible w ubuntu 22.04

### ISSUE THREAD

**Issue by coding-garden-1** [tripedro/SIGNIFY#2]
rose@rosebook:~$ git clone https://github.com/tripedro/SIGNIFY.git
cd SIGNIFY
npm install
Cloning into 'SIGNIFY'...
remote: Enumerating objects: 656, done.
remote: Counting objects: 100% (263/263), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 656 (delta 118), reused 205 (delta 68), pack-reused 393
Receiving objects: 100% (656/656), 1.76 MiB | 4.09 MiB/s, done.
Resolving deltas: 100% (267/267), done.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for parcel@^1.12.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rose/.npm/_logs/2024-04-27T00_31_00_781Z-debug-0.log
rose@rosebook:~/SIGNIFY$ cd SIGNIFY
nano package.json
bash: cd: SIGNIFY: No such file or directory
rose@rosebook:~/SIGNIFY$

**Comment by tripedro** [comment]
Hello,

Try skipping the npm install command, and just run "npm run start", there aren't dependencies that are installed anymore when running the npm install command.

Parcel was used as an original development tool and must still be attempting to be installed.

**Comment by tripedro** [comment]
I also pushed changes to remove parcel, so installing should work fine, but as I said earlier, it's not necessary to install dependencies anymore.

**Comment by coding-garden-1** [comment]
Ok ur right
